### ISSUE TITLE
Z-offset not saving

### ISSUE THREAD

**Issue by JeremyS132** [jojos38/ancubic-kobra-dark-ui#1]
Hello! Recently upgraded to the dark mode and love it. One thing I noticed is that my Z-offset value isn't saving. I set it and tested/calibrated etc. Shut off printer, or it crashed due to hot-end errors and the Z-offset value was reset to 0.

**Comment by JeremyS132** [comment]
User error closing.

**Comment by SineVVAVz** [comment]
Works great and easy on the eyes. It's what Anycubic should have come with. Didn't have to re-level or anything.

Great job!

**Comment by jojos38** [comment]
> ### **[JeremyS132](/JeremyS132) ** commented [7 hours ago](#issue-1316323516)

I had the same issue actually, but it save sometimes? I'm not sure what is the cause. I had my Z-offset to not save twice but all other times it saved fine

**Comment by jojos38** [comment]
> 

Thanks!
