### ISSUE TITLE
Black screen on 2022 anycubic kobra (possibly a DGUS change..?)

### ISSUE THREAD

**Issue by wearrrrr** [jojos38/ancubic-kobra-dark-ui#12]
I was running a FW version that was later than the version you stated, but downgrading went smoothly, it was when I installed this that I was just greeted with a black screen and the anycubic chime, the printer seems to still connect to octoprint, it just really disagrees with this dark ui. I've tried compiling it myself, using your custom firmware, etc, etc, all to no avail. I can get the regular interface (although a little glitchy) back by restoring the stock available FW. It would be nice to at least give a heads up that this won't work for specific DGUS models, as my model is one from February 2022. Any help or insight would be great! Thanks. My discord is wearr#3596 if you want to message me there!

**Comment by jojos38** [comment]
Hi, I'm quite confused about the "Specific DGUS models", as far as I'm aware Anycubic is using the same DGUS model for every Anycubic Kobra and installing back the default firmware should work just fine theoretically.
Can you provide more information on what firmware you try to install please?

**Comment by wearrrrr** [comment]
Hello! I got the Anycubic Kobra this year, and on the blue screen where everything is being installed, the first line reads
`T5L1 DGUS2 V4.7 2022.02.24` <br> I'm not sure if this is normal behavior, but when I boot it up after installing, its still a black screen.

**Comment by jojos38** [comment]
Mh, I'm not using the official motherboard anymore I can't use my screen to compare. I'm sure that the screen is indeed a T5L1 but I'm not sure aobut the DGUS2 part

**Comment by wearrrrr** [comment]
![PXL_20221229_235433853](https://user-images.githubusercontent.com/99224452/210022217-53ab3526-5aa6-42ae-a9ce-9e1fd39e91e0.jpg)
This is an image of the screen, eventually it does succeed.

**Comment by wearrrrr** [comment]
I'm also not sure where I would find the original firmware that came with the printer, because there seems to be no mention of the upgraded firmware online for the screen. (as in the one past 2021)

**Comment by jojos38** [comment]
https://www.anycubic.com/products/kobra

What issues do you have when you install the stock motherboard firmware + screen firmware from this link please?

**Comment by wearrrrr** [comment]
With the stock motherboard firmware + screen firmware the main issue is a really glitchy and borderline unusable interface, i'll attach some photos in a minute.

**Comment by wearrrrr** [comment]
![PXL_20221230_003638065](https://user-images.githubusercontent.com/99224452/210023875-e5792b7c-58b1-4dcf-b7ba-e9042d597f4e.jpg)
![PXL_20221230_003626511](https://user-images.githubusercontent.com/99224452/210023879-c474442b-a4df-492c-8b86-29e571873cea.jpg)
![PXL_20221230_003649918](https://user-images.githubusercontent.com/99224452/210023881-f2d396dd-b69d-4720-bc96-b9dc6eecf49b.jpg)
![PXL_20221230_003642195](https://user-images.githubusercontent.com/99224452/210023883-132c0d90-0af7-40a1-8f09-b56d6ec098ec.jpg)

**Comment by wearrrrr** [comment]
this is really confusing and im not sure what could be causing it.

**Comment by jojos38** [comment]
That is really weird I never seen that, I don't really know what could be the reason either. I think you should contact Anycubic themselves. The official firmware should not cause any issue

**Comment by wearrrrr** [comment]
Yeah I plan on giving anycubic a message to see what is up, hopefully I get a new screen or something, or they tell me how to fix it.

**Comment by wearrrrr** [comment]
Problem solved!!! The SD card that came with the printer is a POS and corrupted the files as they were sending them to the printer's DGUS display, no more corruption, but i'm still not sure if the dark theme will install correctly

**Comment by wearrrrr** [comment]
Everything seems to be working now that im using an actually functioning micro SD card... I have one more quick question though, What tool is used to compile it from scratch, because I can find a link for a DGUS tool that generates a similar file, but the filesize is different and it doesn't work well on the printer. Thanks!

**Comment by jojos38** [comment]
> Everything seems to be working now that im using an actually functioning micro SD card... I have one more quick question though, What tool is used to compile it from scratch, because I can find a link for a DGUS tool that generates a similar file, but the filesize is different and it doesn't work well on the printer. Thanks!

You should use the ICL tool in DGUS Editor, I use 95% compression quality and 4:4:4, it gives great results

**Comment by wearrrrr** [comment]
Thanks a ton! Closing this now because its resolved, i'd suggest adding a warning about the factory sd card to the readme, because they seem to be **really** unreliable
