### ISSUE TITLE
Blank Screen for Settings during Printing

### ISSUE THREAD

**Issue by wabbitguy** [jojos38/ancubic-kobra-dark-ui#13]
When printing, all the buttons show up, including the settings button. If the Settings button is pressed there is a 212 at the top left corner of the LCD. All the buttons normally there are active but there is no display of them. English version 1.1

Be nice to get the hmi to try fixing ourselves if there's a lack of time involved.

**Comment by jojos38** [comment]
I have all the files on my PC I will try to fix that this evening if I have time, along with the 209
Thanks for your error reporting

**Comment by jojos38** [comment]
[DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/10450011/DWIN_SET.zip)
Hey, can you try this version and tell me if it fixed the bug please?
