### ISSUE TITLE
thumbnail preview

### ISSUE THREAD

**Issue by djepsylon** [jojos38/ancubic-kobra-dark-ui#14]
hi, well done for your job!
is it possible to make a thumnail preview on the screen when the host prnt screen appears?
is it possible to have a terminal in your ui?
i ve find the ui of malbuffy (https://github.com/malebuffy/Kobra-Max-Cobra-Kai-UI-and-Firmware) and he have sme cool fuctions and a mix between yours and this one can be cool.
like i ve say in the malbuffy's github, i ve tried to make this changes myself but i don't undurstand how use dgus tool lolll.
is it possible for you to do somme changes or explain me how modify an existing dgus project?

**Comment by jojos38** [comment]
Hi, I'm sorry I don't own a stock Kobra anymore I've changed all the parts so I cannot develop anything anymore for it

But if anyone wants to pull Request changes I'll surely review them
