### ISSUE TITLE
Any chance you'll build this for the TJC screens?

### ISSUE THREAD

**Issue by TTVert** [jojos38/ancubic-kobra-dark-ui#15]
Seems some of us less fortunate ones  have TJC screens, not DWIN screens so we cannot update the screen FW.  :(

Dave

**Comment by jojos38** [comment]
I won't be able to add support for the new screen sadly but I'll keep this issue open so that if anyone wants to they can keep people up to date here

**Comment by TTVert** [comment]
> I won't be able to add support for the new screen sadly but I'll keep this issue open so that if anyone wants to they can keep people up to date here

Understood. Thanks for the reply. Do you know of any source to buy the DWIN screens? I've looked and have had no luck. AC will send another TJC screen unfortunately.

**Comment by TTVert** [comment]
So far in my research I did find [this](https://unofficialnextion.com/t/nextion-and-tjc-whats-the-difference/20). They mention tools for cross compatibility but the tools were in Chinese. Someone found a workaround to display in English but also elaborates much further on the differences between the two. I had read somewhere that there may be insufficient storage to even modify or add images to the TJC screens. With that I am trying to source a DWIN screen presently. Do you know if they are capacitive or resistive screens?

[Here](https://unofficialnextion.com/t/howto-use-tjc-editor-v0-55-for-tjc-panels-in-english/39?page=2) is one version of the english TJC editor. If I find some time I may try to familiarize myself with it as all of the new Kobra printers I believe will be coming w/ the TJC screens.

Thanks
Dave

**Comment by jojos38** [comment]
> So far in my research I did find [this](https://unofficialnextion.com/t/nextion-and-tjc-whats-the-difference/20). They mention tools for cross compatibility but the tools were in Chinese. Someone found a workaround to display in English but also elaborates much further on the differences between the two. I had read somewhere that there may be insufficient storage to even modify or add images to the TJC screens. With that I am trying to source a DWIN screen presently. Do you know if they are capacitive or resistive screens?
> 
> [Here](https://unofficialnextion.com/t/howto-use-tjc-editor-v0-55-for-tjc-panels-in-english/39?page=2) is one version of the english TJC editor. If I find some time I may try to familiarize myself with it as all of the new Kobra printers I believe will be coming w/ the TJC screens.
> 
> Thanks Dave

Hey! Sorry for the long reply I was very busy and completly forgot to answer. I think they're resistive screens but I'm not 100% sure. If you need any help like source files or anything let me know

**Comment by TTVert** [comment]
> > So far in my research I did find [this](https://unofficialnextion.com/t/nextion-and-tjc-whats-the-difference/20). They mention tools for cross compatibility but the tools were in Chinese. Someone found a workaround to display in English but also elaborates much further on the differences between the two. I had read somewhere that there may be insufficient storage to even modify or add images to the TJC screens. With that I am trying to source a DWIN screen presently. Do you know if they are capacitive or resistive screens?
> > [Here](https://unofficialnextion.com/t/howto-use-tjc-editor-v0-55-for-tjc-panels-in-english/39?page=2) is one version of the english TJC editor. If I find some time I may try to familiarize myself with it as all of the new Kobra printers I believe will be coming w/ the TJC screens.
> > Thanks Dave
> 
> Hey! Sorry for the long reply I was very busy and completly forgot to answer. I think they're resistive screens but I'm not 100% sure. If you need any help like source files or anything let me know

Thanks, they certainly are resistive screens.  I'll take anything you've got.

Dave

**Comment by jojos38** [comment]
> > > So far in my research I did find [this](https://unofficialnextion.com/t/nextion-and-tjc-whats-the-difference/20). They mention tools for cross compatibility but the tools were in Chinese. Someone found a workaround to display in English but also elaborates much further on the differences between the two. I had read somewhere that there may be insufficient storage to even modify or add images to the TJC screens. With that I am trying to source a DWIN screen presently. Do you know if they are capacitive or resistive screens?
> > > [Here](https://unofficialnextion.com/t/howto-use-tjc-editor-v0-55-for-tjc-panels-in-english/39?page=2) is one version of the english TJC editor. If I find some time I may try to familiarize myself with it as all of the new Kobra printers I believe will be coming w/ the TJC screens.
> > > Thanks Dave
> > 
> > 
> > Hey! Sorry for the long reply I was very busy and completly forgot to answer. I think they're resistive screens but I'm not 100% sure. If you need any help like source files or anything let me know
> 
> Thanks, they certainly are resistive screens. I'll take anything you've got.
> 
> Dave

Hey, I'm sorry I completely missed your answer, after thinking about it everything you can get is pretty much on the repo already, there is not much more I can provide that would be useful for you I think. Sorry for the late answer

**Comment by TTVert** [comment]
> > > > So far in my research I did find [this](https://unofficialnextion.com/t/nextion-and-tjc-whats-the-difference/20). They mention tools for cross compatibility but the tools were in Chinese. Someone found a workaround to display in English but also elaborates much further on the differences between the two. I had read somewhere that there may be insufficient storage to even modify or add images to the TJC screens. With that I am trying to source a DWIN screen presently. Do you know if they are capacitive or resistive screens?
> > > > [Here](https://unofficialnextion.com/t/howto-use-tjc-editor-v0-55-for-tjc-panels-in-english/39?page=2) is one version of the english TJC editor. If I find some time I may try to familiarize myself with it as all of the new Kobra printers I believe will be coming w/ the TJC screens.
> > > > Thanks Dave
> > > 
> > > 
> > > Hey! Sorry for the long reply I was very busy and completly forgot to answer. I think they're resistive screens but I'm not 100% sure. If you need any help like source files or anything let me know
> > 
> > 
> > Thanks, they certainly are resistive screens. I'll take anything you've got.
> > Dave
> 
> Hey, I'm sorry I completely missed your answer, after thinking about it everything you can get is pretty much on the repo already, there is not much more I can provide that would be useful for you I think. Sorry for the late answer

No worries, thanks for the follow up.
