### ISSUE TITLE
LCD DMG80480C043

### ISSUE THREAD

**Issue by Aergernis** [jojos38/ancubic-kobra-dark-ui#16]
Hi,
i've a old DWIN display here  and wanted to use it for the Kobra max (i think it's from an old viper). Sadly the screen is rotated.

Is it possible to rotate it and adopt the ui for the lcd DMG80480C043?

**Comment by jojos38** [comment]
Hey, sorry it is not easily doable I won't be able to do it myself as I don't use any screen anymore
