### ISSUE TITLE
Edit design

### ISSUE THREAD

**Issue by maris-mc** [jojos38/ancubic-kobra-dark-ui#17]
Hi,
I wanted to create my own design for my printer but unfortunately I can't run the file on Windows. How do I have to execute the index.js file so that I can convert my code?

**Comment by jojos38** [comment]
Hi, you need to install Node.js, then you need to open a terminal in the folder and type in "node index.js" and that's all

**Comment by maris-mc** [comment]
Thank you for your answer,
Unfortunately I get this error message: (node:38652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:38652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:38652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit
C:\Users\maris.cremer\Desktop\UI\node_modules\pageres\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:204
            reject(new Errors_js_1.TimeoutError(`Timed out after ${timeout} ms while trying to connect to the browser! Only Chrome at revision r${preferredRevision} is guaranteed to work.`));
                   ^

TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r818858 is guaranteed to work.
    at Timeout.onTimeout (C:\Users\maris.cremer\Desktop\UI\node_modules\pageres\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:204:20)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.9.0

I hope you can help me

**Comment by maris-mc** [comment]
> Hi, you need to install Node.js, then you need to open a terminal in the folder and type in "node index.js" and that's all

Thank you for your answer,
Unfortunately I get this error message: (node:38652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use node --trace-warnings ... to show where the warning was created)
(node:38652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:38652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:38652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit
C:\Users\maris.cremer\Desktop\UI\node_modules\pageres\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:204
reject(new Errors_js_1.TimeoutError(Timed out after ${timeout} ms while trying to connect to the browser! Only Chrome at revision r${preferredRevision} is guaranteed to work.));
^

TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r818858 is guaranteed to work.
at Timeout.onTimeout (C:\Users\maris.cremer\Desktop\UI\node_modules\pageres\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:204:20)
at listOnTimeout (node:internal/timers:573:17)
at process.processTimers (node:internal/timers:514:7)

Node.js v20.9.0

I hope you can help me

**Comment by jojos38** [comment]
I'm not sure why you get this error, do you have edge or IE installed? Are you on Windows?

**Comment by maris-mc** [comment]
> I'm not sure why you get this error, do you have edge or IE installed? Are you on Windows?

I use Windows and have Edge and IE installed but when I open IE, Edge opens instead. I use Brave, a browser based on Chromium, as my normal browser.

**Comment by jojos38** [comment]
> > I'm not sure why you get this error, do you have edge or IE installed? Are you on Windows?
> 
> I use Windows and have Edge and IE installed but when I open IE, Edge opens instead. I use Brave, a browser based on Chromium, as my normal browser.

Well I'm dumb I forgot something, can you run the command "npm install" in the folder where index.js is located and try again

**Comment by maris-mc** [comment]
> > > I'm not sure why you get this error, do you have edge or IE installed? Are you on Windows?
> > 
> > 
> > I use Windows and have Edge and IE installed but when I open IE, Edge opens instead. I use Brave, a browser based on Chromium, as my normal browser.
> 
> Well I'm dumb I forgot something, can you run the command "npm install" in the folder where index.js is located and try again

The same error still comes up

**Comment by maris-mc** [comment]
The same error still comes up

**Comment by jojos38** [comment]
I'm not sure then sorry, maybe try Node.js 18 or 16 but I'm not sure

**Comment by maris-mc** [comment]
> I'm not sure then sorry, maybe try Node.js 18 or 16 but I'm not sure

Ok, I tried it, but it doesn't work :(

**Comment by jojos38** [comment]
> > I'm not sure then sorry, maybe try Node.js 18 or 16 but I'm not sure
> 
> Ok, I tried it, but it doesn't work :(

I'm sorry I have no idea then
