### ISSUE TITLE
Not able to install. jut 0 0 0 0 files 

### ISSUE THREAD

**Issue by Solilord** [jojos38/ancubic-kobra-dark-ui#2]
Hey! 

iam not able to install your UI. 

I checked the Fw and UI version. its correct. 

I prepared my SD Card (32 GB SanDisk) 
Structure looks like this:
![grafik](https://user-images.githubusercontent.com/8177636/180836638-97952000-7478-45dd-b5fc-f2161ed60b9c.png)

The Printer Starts up, display shows immediatly the blue screen with SD Card ..... END
and every file extension is 0 :/ 

I tried creeating the DWIN_SET Folder by myself and pasting the files in there but no help.

**Comment by Solilord** [comment]
Wtf... it was the SD Card. 

I tried the cheap factory card. Now it works. Maybe some formating issue?

**Comment by SineVVAVz** [comment]
Yes, it could have been the format. Make sure to use same format is OEM card. Great to know you got it working!

**Comment by Solilord** [comment]
Mhh. I checked the other one: Its Fat32 as well. 
is it size related? or Type? the SanDisk is microSD HC 
Maybe recommending to use the factorycard is an idea for the readme

**Comment by SineVVAVz** [comment]
Your probably right.

**Comment by jojos38** [comment]
For future reference, according to the official documentation the SD card need to use 4096 bytes sector size, that probably was your issue
