### ISSUE TITLE
Overlapping "°C"

### ISSUE THREAD

**Issue by Solilord** [jojos38/ancubic-kobra-dark-ui#3]
Heya. 
I noticed that the top bar is overlapping the "°C" on the nozzle side.

![image](https://user-images.githubusercontent.com/8177636/180863211-b954760c-6de9-4d05-83e8-962e4004c66c.jpeg)

It doesn't bother me that much, but maybe it can be fixed for next release ;)

**Comment by jojos38** [comment]
Hey, thanks for reporting the issue I'll try to fix this asap by moving the C a bit to the right

**Comment by jojos38** [comment]
[16_68_.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/9190645/16_68_.zip)
Would you be able to try to flash that ICL file please and tell me if it worked? I don't have my printer for now
You just need to follow the installation steps as usual but just put that .ICL file in the DWIN Folder, you don't need anything else

**Comment by Solilord** [comment]
i will try it as soon as i can. (probably tomorrow morning)
Right now i have a 28h Print running :D

**Comment by jojos38** [comment]
Alright haha, I leave home tomorrow hence why I cannot, take your time it's not urgent and good luck for the print

**Comment by SineVVAVz** [comment]
I can try it in another hour. Just use that zip above correct?

**Comment by jojos38** [comment]
> I can try it in another hour. Just use that zip above correct?

Thanks!
Yep just drop the .icl file that is in the zip in a DWIN_SET folder on your SD card and that's all

**Comment by SineVVAVz** [comment]
Know what? I just noticed that mine is fine off your original file. Wonder why his is acting different. ![image](https://user-images.githubusercontent.com/63254465/181056887-c5e3c123-cf61-476a-89d0-a5f325785173.jpeg)

**Comment by Solilord** [comment]
On main screen it's fine as well. 
It's in any of the subpages (orange top)
I can't find it now and don't want to click around. I don't wanna mess up my huge print.

Edit: but i didnt notice that the shift isnt on all pages.. strange. 
Maybe you can check all subsites.

**Comment by jojos38** [comment]
It might be my CSS code actually? Or maybe the text isn't centered in every textbox or something like this, I will try to see if I can find the issue but I won't have much time so it probably will be next week

**Comment by SineVVAVz** [comment]
I only have the temp shown on my main page. All sub pages just have the title of the sub on top. Am I missing something here? All subs are the same as pictured just different titles and colors but no temp.
![image](https://user-images.githubusercontent.com/63254465/181071612-31e367f0-ff70-47a2-b834-8a6167e1c5f7.jpeg)

**Comment by Solilord** [comment]
Ahh. I remeber where.

Start Auto-Leveling! This is the only one with orange top and temps on top :D 
Okay, not the biggest Issue but yesterday i thought this bug would be everywhere :D

**Comment by SineVVAVz** [comment]
Ahh HA! I found what you are talking about. I'll run the test code and see what happens

**Comment by SineVVAVz** [comment]
Yup...it's still there after I updated it with the new file. 

No rush on the fix as it's just aesthetics. Been printing fine so far. ![image](https://user-images.githubusercontent.com/63254465/181082056-09de3bff-651d-456b-9547-b5421e4a7992.jpeg)

**Comment by jojos38** [comment]
[DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/9192603/DWIN_SET.zip)
After further investigation I think this is a firmware bug from the motherboard, the font doesn't seem to be the same size between both?? Can you guys try this one and tell me if it works please
We don't have the source code of the firmware yet sadly

**Comment by SineVVAVz** [comment]
Will do. Waiting for a print to finish shortly

**Comment by jojos38** [comment]
Also, the above file should not completely fix the issue as the text will still differ from the original, but it should at least not overlap anymore on the °C

**Comment by SineVVAVz** [comment]
It's better. Seems like it's needs another "push" over but it's close!

![image](https://user-images.githubusercontent.com/63254465/181095976-248883ea-2df1-4b4d-965e-1eb5de0c7af5.jpeg)

![image](https://user-images.githubusercontent.com/63254465/181095996-4b08b2a0-400a-4fd4-9ba5-27ee6992e0af.jpeg)

**Comment by jojos38** [comment]
This one should be good, I moved it one pixel more to the left. If it's still too much to the right I will move it one pixel further and call it a day as I believe the text is one or two pixel away from the °C for others

Thank you very much for your time and for testing by the way

**Comment by SineVVAVz** [comment]
Drop all 3 files in or just the .icl?

**Comment by jojos38** [comment]
[Desktop.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/9192877/Desktop.zip)
My bad, didn't mean the put the .ICL sorry, here is the right one

**Comment by SineVVAVz** [comment]
Your welcome BTW...and Thank you for making a sweet GUI! Wish this dang thing had more adjustments for a filament change. 

Got ya. Going to try it after another test print finishes in 5 mins

**Comment by jojos38** [comment]
> Your welcome BTW...and Thank you for making a sweet GUI! Wish this dang thing had more adjustments for a filament change.
> 
> Got ya. Going to try it after another test print finishes in 5 mins

If they release the firmware to the public I'll start touching the firmware and more important changes hopefully
I already contacted them I'm waiting for their answer

**Comment by SineVVAVz** [comment]
Ok well I think the one before this was better. This has a big gap now.

![image](https://user-images.githubusercontent.com/63254465/181100267-6933b89d-d370-4898-a5f6-57242bccca76.jpeg)

![image](https://user-images.githubusercontent.com/63254465/181100293-d55d69d4-c5b7-4d2c-a15d-95ed8aa76158.jpeg)

**Comment by jojos38** [comment]
I really don't get it at this point, the only difference between the first one and the second one was the X position which I moved by one pixel. If you look closely you'll see that the character spacing between the first and the second is not the same. I don't really understand what's happening here

**Comment by jojos38** [comment]
The font you have here on the last photo is the right one btw, this would've worked if the text was placed like any other page. But if I place it like "any other page" then the font seems to change and it's off

**Comment by SineVVAVz** [comment]
No worries. I think it's good to go for now if you can just update you assets to the one before this. At least there is a small gap. It's just my OCD...lol. People should be happy it works given the fact that they have't released the code and I'm sure you'll revamp it when and if they do release it. *Fingers Crossed*

**Comment by jojos38** [comment]
> No worries. I think it's good to go for now if you can just update you assets to the one before this. At least there is a small gap. It's just my OCD...lol. People should be happy it works given the fact that they have't released the code and I'm sure you'll revamp it when and if they do release it. _Fingers Crossed_

They released the code for the Vyper so I would expect them to release the code for the Kobra but maybe they have some delay like 1 year after the printer release or some stuff like this. Let's see I guess

Either way, I will release the file before the last one as you said, thank you very much for your help as well as @Solilord

**Comment by jojos38** [comment]
I'm just adding a comment to tell you about the answer from Anycubic, as expected we will get the source code for the firmware in 2 to 3 months. Lets be patient haha
