### ISSUE TITLE
Power on reboot

### ISSUE THREAD

**Issue by SineVVAVz** [jojos38/ancubic-kobra-dark-ui#5]
May just want to leave a note somewhere that you have to unplug the power cable for 20 seconds so that the caps can discharge. Then plug back in and reboot in order to update to your GUI via the SC card in the screen. At first I did it without unplugging and it wouldn't take the update. Don't know if you already noted that but just a heads up. Doing a second printer hence why I noticed the issue. Thanks again for this sweet GUI!

**Comment by jojos38** [comment]
Hey, thanks for the report that's weird I never had this but I'll add it just in case
