### ISSUE TITLE
Wrong title in Change Filament screen

### ISSUE THREAD

**Issue by gekart** [jojos38/ancubic-kobra-dark-ui#8]
Excellent job! But there is a minor glitch in Change Filament. The screen name is z-offset (top-most title).

https://github.com/jojos38/anycubic-kobra-dark-ui/pull/9

However, it would be nice to have an additional z-axis 50% button in that screen. Where is the actual UI code to implement that feature?

**Comment by jojos38** [comment]
> 

Hey, I'm sorry I have discontinued this UI as I changed my motherboard, if I can get it to work with the new motherboard I'll get back on it though. The code is located in the Marlin firmware in screen or something like that
